### ISSUE TITLE
自动保存的json文件无法转格式

### ISSUE THREAD

**Issue by 25321** [WhiteMinds/LiveAutoRecord#100]
后台录制后视频旁自动生成的json弹幕文件，转ass格式后弹幕文字全部消失。在其他渠道下载的json弹幕文件就不会出现此情况，不知道是本软件的json弹幕文件本来就无法使用还是什么，保存的srt弹幕文件可以使用。求解

**Comment by WhiteMinds** [comment]
这个 json 内的 schema 是私有的，我不知道你是用什么软件转换成 ass 的，它不太可能支持所有私有的 schema。

你可以考虑转成 srt 后再转成 ass，因为这两个都是公开的格式。
