### ISSUE TITLE
启动无内容怎么解决……

### ISSUE THREAD

**Issue by jm3720343** [WhiteMinds/LiveAutoRecord#106]
![微信截图_20230824124336](https://github.com/WhiteMinds/LiveAutoRecord/assets/143060008/b37245d7-80df-4c23-8e7a-c4c8a1fde3c2)
![微信截图_20230824124343](https://github.com/WhiteMinds/LiveAutoRecord/assets/143060008/251a38e7-42c7-4dde-892a-05bedc37d382)
某天晚上电脑挂机录制突然跳闸，第二天再打开就这样了。卸载重新安装也没用啊。

**Comment by WhiteMinds** [comment]
是一个已知问题：

Duplicate of #88
