### ISSUE TITLE
存储路径问题

### ISSUE THREAD

**Issue by 23clot** [WhiteMinds/LiveAutoRecord#108]
新人 系统的储存路径怎么找不到 可以修改路径吗

**Comment by WhiteMinds** [comment]
你是说配置文件的存储路径，还是录像的存储路径？

**Comment by 23clot** [comment]
我在访达中一直没有找到 还有就是没录制一次就会出现一次json文件吗

**Comment by WhiteMinds** [comment]
> 我在访达中一直没有找到 还有就是没录制一次就会出现一次json文件吗

json 是存弹幕的，一般和录像是在一起的，可能录制出问题了，你试试录其他直播间或其他平台是否正常？

**Comment by 23clot** [comment]
这个路径好难改 我想改到我的移动硬盘上

**Comment by WhiteMinds** [comment]
> 这个路径好难改 我想改到我的移动硬盘上

我觉得你可以先解决录制失败的问题，改路径只需要把非变量的部分调整掉就可以了。

**Comment by Gh-37** [comment]
> 新人 系统的储存路径怎么找不到 可以修改路径吗


> 这个路径好难改 我想改到我的移动硬盘上

请问你改好了吗？我也不会改，我改了原本默认存到C盘的设置，改成存到别的盘之后我就录不了了，不知道怎么设置回去

**Comment by WhiteMinds** [comment]
> 请问你改好了吗？我也不会改，我改了原本默认存到C盘的设置，改成存到别的盘之后我就录不了了，不知道怎么设置回去

默认的路径是软件数据文件夹 + `{platform}/{owner}/{year}-{month}-{date} {hour}-{min}-{sec} {title}.mp4`，后面这一串是录像开始时决定创建的录像文件所在的文件夹和文件名。

比如你决定放在 `D:\data` 下，那么可以写：`D:\data\{platform}\{owner}\{year}-{month}-{date} {hour}-{min}-{sec} {title}.mp4`

**Comment by Gh-37** [comment]
> > 请问你改好了吗？我也不会改，我改了原本默认存到C盘的设置，改成存到别的盘之后我就录不了了，不知道怎么设置回去
> 
> 默认的路径是软件数据文件夹 + `{platform}/{owner}/{year}-{month}-{date} {hour}-{min}-{sec} {title}.mp4`，后面这一串是录像开始时决定创建的录像文件所在的文件夹和文件名。
> 
> 比如你决定放在 `D:\data` 下，那么可以写：`D:\data\{platform}\{owner}\{year}-{month}-{date} {hour}-{min}-{sec} {title}.mp4`

太感谢了！！修改成功了，录上了✌

**Comment by 23clot** [comment]
如果是mac版本呢  这个存储路径该怎么修改呢

**Comment by 23clot** [comment]
<img width="470" alt="image" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/75904250/4b349722-fa4e-462d-824b-ec9d81eec781">
如何重置  现在终止无效了

**Comment by WhiteMinds** [comment]
> 如果是mac版本呢 这个存储路径该怎么修改呢

一样的

> 如何重置 现在终止无效了

存储路径感觉不应该引起无法终止的问题，存储路径设置的是什么？你是稳定复现这个问题吗？其他直播间是否正常？
