### ISSUE TITLE
自动分段后主动终止录制问题

### ISSUE THREAD

**Issue by q1518001822** [WhiteMinds/LiveAutoRecord#111]
改成了自动分段输出在主动终止录制后视频文件无法观看 主播下播后会不会也这样目前不知道  字幕文件也没有分段

**Comment by WhiteMinds** [comment]
截图或者复制看看配置的参数是什么，字幕文件确实是没分段的，因为软件本身还没支持分段的功能，这个分段只是基于 ffmpeg 的参数临时用一下

**Comment by q1518001822** [comment]
&nbsp;


云飞＆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WhiteMinds/LiveAutoRecord] 自动分段后主动终止录制问题 (Issue #111)





 
截图或者复制看看配置的参数是什么，字幕文件确实是没分段的，因为软件本身还没支持分段的功能，这个分段只是基于 ffmpeg 的参数临时用一下

**Comment by WhiteMinds** [comment]
你这个邮件回复的有问题，直接在 github 上回吧

**Comment by q1518001822** [comment]
![PL 3(ZKBAWN85_J~PKY}QZ8](https://github.com/WhiteMinds/LiveAutoRecord/assets/143792420/e6a495c0-46f7-4dcb-a615-4979fc6fb28e)

**Comment by q1518001822** [comment]
![{X `0U)_KQVQ}G07_QJH BC](https://github.com/WhiteMinds/LiveAutoRecord/assets/143792420/15e85b82-ff63-489a-ac7e-8a6e3501cf2b)
主动终止会留下这2文件

**Comment by WhiteMinds** [comment]
你录制了多长时间，录制后的文件大小是多少，播放不了是指内置播放器放不了还是内置播放器与其他你尝试的播放器都无法播放，如果你尝试了外部播放器可以说一下外部播放器的名字。
另外还可以试试把分段时间设短一点比如一分钟，看一下自动分出第二段时，第一段能否正常播放了。

**Comment by q1518001822** [comment]
2-3分钟  71mb   内外都放不了 主动终止后内部也没有录制记录  啥播放器都不行 potplayer 以及一些普通播放器都不行 最后你说的一分钟自动我试了是没问题的 所以才说主动中断有问题

**Comment by WhiteMinds** [comment]
> 2-3分钟 71mb 内外都放不了 主动终止后内部也没有录制记录 啥播放器都不行 potplayer 以及一些普通播放器都不行 最后你说的一分钟自动我试了是没问题的 所以才说主动中断有问题

那可能确实终止的实现有些问题，但是或许是解决不了的，因为已经是通过标准的 SIGINT 信号退出了。
这种损坏了的不知道能不能额外手动通过 ffmpeg 处理修复，或者有没有什么其他 ffmpeg 参数来实现类似的效果。

因为软件真正实现分段功能可能是很久之后了，我很少有时间来继续维护这个软件。

**Comment by q1518001822** [comment]
我有个同类软件就是录的flv格式 带自动转换mp4  你可以考虑一下加一个flv自动转换mp4的功能  flv格式我试了是能用的 就是自己转换太慢了

**Comment by WhiteMinds** [comment]
> 我有个同类软件就是录的flv格式 带自动转换mp4 你可以考虑一下加一个flv自动转换mp4的功能 flv格式我试了是能用的 就是自己转换太慢了

你改后缀名可以录 flv 格式，因为是直接作为 output 传递给 ffmpeg 的，不过 ffmpeg 参数也得改，具体咋调不确定。
录制完了之后再执行一个 ffmpeg 这个感觉复杂度加的有点多了，做这个不如直接实现分段功能。

**Comment by q1518001822** [comment]
知道改后缀可以录就是不好转换 另外有办法下载带弹幕的视频吗

**Comment by WhiteMinds** [comment]
> 另外有办法下载带弹幕的视频吗

软件可以提供 srt 类型的字幕，得手动的通过 ffmpeg 或者其他软件合成到视频上。

> 初始全局设置的路径参数是什么

默认的存储路径是 `软件数据文件夹` + `{platform}/{owner}/{year}-{month}-{date} {hour}-{min}-{sec} {title}.mp4`

**Comment by q1518001822** [comment]
还有默认输出参数
