### ISSUE TITLE
为什么我的软件突然用不了了 

### ISSUE THREAD

**Issue by Gh-37** [WhiteMinds/LiveAutoRecord#117]
打开全是空白的，转圈的
![20230928210239](https://github.com/WhiteMinds/LiveAutoRecord/assets/144473598/10ac6739-4f56-47a6-977f-5a813ca42b4e)
![20230928210637](https://github.com/WhiteMinds/LiveAutoRecord/assets/144473598/68a682a6-3e7b-4ae9-8a24-4b0573bb2a22)

**Comment by WhiteMinds** [comment]
应该是这个问题：#88 
你可以参考里面的临时解决方案来处理下。
