### ISSUE TITLE
在挂着代理的情况下可能会导致录制一直无法开始

### ISSUE THREAD

**Issue by WhiteMinds** [WhiteMinds/LiveAutoRecord#121]
点刷新会一直处于 loading 状态。

可能的解决方案是提供一个显式的代理配置项，而不是依赖默认的从 https_proxy 环境变量中读取。

**Comment by popularhoney** [comment]
今天一直没录到 这个情况怎么解决

**Comment by WhiteMinds** [comment]
你没录到应该不是这个问题，#120 是另一个问题

**Comment by popularhoney** [comment]
刷新了一直在转 昨天一天都没工作 之前是开录录不全 现在压根不开始



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 上午8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WhiteMinds/LiveAutoRecord] 在挂着代理的情况下可能会导致录制一直无法开始 (Issue #121)




 
你没录到应该不是这个问题，#120 是另一个问题

**Comment by WhiteMinds** [comment]
> 刷新了一直在转 昨天一天都没工作 之前是开录录不全 现在压根不开始

一直在转的话那大概率是网络问题，有可能是挂了代理问题，但你录的抖音我感觉更大概率是 #102 这个问题，你可以匿名访问网页版抖音看看是不是被 ban 了。

**Comment by WhiteMinds** [comment]
> 我试了一下 b站能录 这种情况怎么办啊

抖音录不了的问题要等 #102 解决，然后里面有提到临时的解决方案你可以试试

**Comment by WhiteMinds** [comment]
代理导致录制不开始的 bug 在 4.4.0 中修复了。
