### ISSUE TITLE
请问可以录制直播时哪个观众进入了直播间的情况吗？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [WhiteMinds/LiveAutoRecord#122]
请问可以录制直播时哪个观众进入了直播间的情况吗？

**Comment by WhiteMinds** [comment]
这种属于弹幕信息（或者说视频之外的额外信息），有的平台可以录制有的不行，看具体的弹幕客户端实现，和录制礼物是一个道理，大概率平台不会提供完整的进出信息。

**Comment by zihaoxingstudy1** [comment]
> 这种属于弹幕信息（或者说视频之外的额外信息），有的平台可以录制有的不行，看具体的弹幕客户端实现，和录制礼物是一个道理，大概率平台不会提供完整的进出信息。

哦哦，好的，请问抖音平台的可以嘛

**Comment by WhiteMinds** [comment]
> 哦哦，好的，请问抖音平台的可以嘛

抖音目前是不支持的

**Comment by WhiteMinds** [comment]
该问题之后在 #179 中跟踪。
