### ISSUE TITLE
录制开始发出通知不起作用了

### ISSUE THREAD

**Issue by CHDKBL** [WhiteMinds/LiveAutoRecord#125]
win10系统的通知我是打开着的，但是软件开始录的时候不会弹通知窗口。试过重装软件并且删除appdata里的相关文件，但还是不行。
![Screenshot 2023-11-04 170626](https://github.com/WhiteMinds/LiveAutoRecord/assets/95182638/cd92affb-c00b-4277-99ee-7ed75bb8ee2f)

**Comment by WhiteMinds** [comment]
我不太确定 win10 是否还有一个总的通知开关，你可以检查下。
以及检查下软件内的录制时通知选项是否是已勾选的。

**Comment by CHDKBL** [comment]
> 我不确定win10是否还有一个总的通知开关，你可以检查下。 以及检查下软件内的录制时通知选项是否是已勾选的。

解决了，是微软系统的问题，https://zhuanlan.zhihu.com/p/370045691。

**Comment by WhiteMinds** [comment]
> 解决了，是微软系统的问题，[https://zhuanlan.zhihu.com/p/370045691。](https://zhuanlan.zhihu.com/p/370045691%E3%80%82)

amazing 🫠
