### ISSUE TITLE
部分云盘不支持特殊字符如表情符号，需要一些方式来配置将这些字符从保存路径中移除掉

### ISSUE THREAD

**Issue by wwkk2580** [WhiteMinds/LiveAutoRecord#126]

**Comment by wwkk2580** [comment]
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/76099203/eb058242-93a9-47b4-9dbe-97ca2de465d5)

**Comment by WhiteMinds** [comment]
这个也可能别人会想保留，但是单独做出一个配置项又没什么必要。
这个表情符号会带来什么问题吗？

**Comment by wwkk2580** [comment]
> 这个也可能别人会想保留，但是单独做出一个配置项又没什么必要。 这个表情符号会带来什么问题吗？

无法上传到云盘

**Comment by WhiteMinds** [comment]
> 无法上传到云盘，会提示文件名或路径违规

你可以考虑把 owner 变量换成 channelId 变量

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/7b445163-a415-48a7-8448-029ad6ccdba9)

**Comment by wwkk2580** [comment]
> > 无法上传到云盘，会提示文件名或路径违规
> 
> 你可以考虑把 owner 变量换成 channelId 变量
> 
> ![image](https://user-images.githubusercontent.com/9160743/280606677-7b445163-a415-48a7-8448-029ad6ccdba9.png)

这样的话要找一个主播好难🤔

**Comment by wwkk2580** [comment]
希望增加一个配置项吧，感谢

**Comment by WhiteMinds** [comment]
> 希望增加一个配置项吧，感谢

这个场景不太常规，因为有的云盘可能是支持 emoji 的，因为系统都支持 emoji 所以这个配置项也不能叫做 “排除系统不支持的字符”，但是配置项叫 “支持某某云盘的字符” 又很怪。

我感觉可以新加一个变量 remarks，这个变量是指向频道的 “备注” 的，然后备注现在添加频道时是会自动设置为主播名的，你可以手动删掉里面不需要的字符，然后把 owner 变量换成备注用的 remarks 变量。

**Comment by WhiteMinds** [comment]
这个变量添加起来应该挺简单的，你要不要考虑来个 PR。

**Comment by wwkk2580** [comment]
> 这个变量添加起来应该挺简单的，你要不要考虑来个 PR。

我不是开发，我是测试😂

**Comment by WhiteMinds** [comment]
在新版本中为保存路径规则实现了 remarks（备注）变量。

https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.5.0
