### ISSUE TITLE
打开MP4视频文件后发现时间只有1分钟，但是到头了之后可以继续播放

### ISSUE THREAD

**Issue by diklios5768** [WhiteMinds/LiveAutoRecord#128]
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/47837462/8d3a7c6a-29ca-48cd-bd27-2a89ca3d12dd)
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/47837462/ab9b05ef-1c6b-4f06-912c-8161e575ded3)
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/47837462/673ef45c-7f12-49f9-87be-b0d277da0e5e)

虽然只显示1分钟，但是仍然可以播放，在potplayer、Windows系统自带的media player和一些其他播放器中都是这样，但是在暴风影音、MPC-BE、VLC中没有出现这样的情况。

目前暂时使用转一次码的方法进行解决

**Comment by WhiteMinds** [comment]
因为默认的 ffmpegOutputs 我配置的是 fmp4，有些播放器可能不支持
