### ISSUE TITLE
录制完成后，使用其他播放器显示时长仅一分钟，使用录屏自带播放器能正常播放

### ISSUE THREAD

**Issue by 931677309** [WhiteMinds/LiveAutoRecord#134]

**Comment by 931677309** [comment]
使用的播放器是迅雷影音和windows media player,均显示时长一分钟

**Comment by WhiteMinds** [comment]
Duplicate: https://github.com/WhiteMinds/LiveAutoRecord/issues/101#issuecomment-1683258240
