### ISSUE TITLE
录制任务较多时，可能会出现自动录制无法正常工作的情况，手动刷新仍然可以工作，猜测可能是自动录制的检查过程被某个频道的错误打断了

### ISSUE THREAD

**Issue by Ju9aad** [WhiteMinds/LiveAutoRecord#135]
录制任务很多，不知道为什么自动录制无法进行，需要手动刷新才可

**Comment by WhiteMinds** [comment]
是全部都不自动，还是部分不自动，这些不自动录制的频道有什么一样的特征，比如说它们都是一个平台的？或者都是户外的？

**Comment by Ju9aad** [comment]
全部都无法自动了，斗鱼虎牙都不行

**Comment by Ju9aad** [comment]
而且卸载之后 重新安装也不管用 而且原来添加的那些主播怎么都还在

**Comment by WhiteMinds** [comment]
> 全部都无法自动了，斗鱼虎牙都不行

那挺奇怪的，会不会是选项里勾了不自动检查，因为手动点刷新仍然能录制的话就说明检查单个直播间是否开播的功能还是有效的，只是自动检查的逻辑没执行。

如果是 bug 的话，那问题只能出在自动检查那块，我目前简单过了下相关的代码，看不出来哪里会有问题。

> 而且卸载之后 重新安装也不管用 而且原来添加的那些主播怎么都还在

卸载这块确实做的不够干净，配置文件没有在卸载时移除，这些文件在：https://github.com/WhiteMinds/LiveAutoRecord/issues/88#issuecomment-1685522219

**Comment by Ju9aad** [comment]
> > 全部都无法自动了，斗鱼虎牙都不行
> 
> 那挺奇怪的，会不会是选项里勾了不自动检查，因为手动点刷新仍然能录制的话就说明检查单个直播间是否开播的功能还是有效的，只是自动检查的逻辑没执行。
> 
> 如果是 bug 的话，那问题只能出在自动检查那块，我目前简单过了下相关的代码，看不出来哪里会有问题。
> 
> > 而且卸载之后 重新安装也不管用 而且原来添加的那些主播怎么都还在
> 
> 卸载这块确实做的不够干净，配置文件没有在卸载时移除，这些文件在：[#88 (comment)](https://github.com/WhiteMinds/LiveAutoRecord/issues/88#issuecomment-1685522219)
> 
> > 频道配置文件 %LOCALAPPDATA%\live-auto-record\Data\data.json
> > 全局录制配置文件 %APPDATA%\live-auto-record\Config\manager.json
> > 应用配置文件 %APPDATA%\live-auto-record\Config\settings.json

不自动检查那块我验证了的，没勾选，我觉得可能还是录制主播太多的缘故？前几天虎牙有个舞蹈比赛，我就多录了几十个，导致斗鱼虎牙都无法自动录制，前几天我删除了大把，剩下30-40个，又可以自动录制了，我不太懂代码，不太清楚哪里的问题，按理说如果是风控的问题，那虎牙添加的主播应该不会影响斗鱼的自动录制，但他影响了，不知道为啥

**Comment by WhiteMinds** [comment]
> 那虎牙添加的主播应该不会影响斗鱼的自动录制，但他影响了，不知道为啥

这个确实有可能，某个频道检查抛出了意料之外的错误可能会打断整个检查循环，这里设计的有点问题。

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/ce373c35-6a7f-437f-80df-8d338e612fb0)

> 前几天我删除了大把，剩下30-40个，又可以自动录制了

那要么是删除的频道里有打断检查循环的那些频道，或者是检查频率问题，可以试试把检查频率调低一些，从默认的 1 秒一次调到 2 秒一次看看是不是就能多录一些了。

**Comment by Ju9aad** [comment]
> > 那虎牙添加的主播应该不会影响斗鱼的自动录制，但他影响了，不知道为啥
> 
> 这个确实有可能，某个频道检查抛出了意料之外的错误可能会打断整个检查循环，这里设计的有点问题。
> 
> ![image](https://private-user-images.githubusercontent.com/9160743/290743002-ce373c35-6a7f-437f-80df-8d338e612fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjM5MjcsIm5iZiI6MTcwMjcyMzYyNywicGF0aCI6Ii85MTYwNzQzLzI5MDc0MzAwMi1jZTM3M2MzNS02YTdmLTQzN2YtODBkZi04ZDMzOGU2MTJmYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTA0NzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjYTQ0NzZiZjdiYmViYzlmZGQ0Y2I2MWM0NzY2MjRjYzU0OGEyZGU2Yzc0NWNjYWU1YjExZTA3ZDA4OWQwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hqlRTWeqms5hwavNiDHH06X9VUlYCehh7hiWdLgFNoE)
> 
> > 前几天我删除了大把，剩下30-40个，又可以自动录制了
> 
> 那要么是删除的频道里有打断检查循环的那些频道，或者是检查频率问题，可以试试把检查频率调低一些，从默认的 1 秒一次调到 2 秒一次看看是不是就能多录一些了。

好的，后续需要录的主播多了我再试试。

**Comment by WhiteMinds** [comment]
新版本中修复了检查循环被意外打断的问题 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.7.0
