### ISSUE TITLE
有的任务一下一直转圈 无法恢复

### ISSUE THREAD

**Issue by Ju9aad** [WhiteMinds/LiveAutoRecord#136]
![微信截图_20231208172248](https://github.com/WhiteMinds/LiveAutoRecord/assets/97628900/8db7017c-46aa-412c-8e59-e3f5d0bfe319)

**Comment by Ju9aad** [comment]
据我的发现是刷新几个违规的直播间会导致后面的刷新一直无法更新

**Comment by WhiteMinds** [comment]
> 据我的发现是刷新几个违规的直播间会导致后面的刷新一直无法更新

这个能确定吗，有尝试过只录制一个正常直播间 + 一个违规直播间的情况吗，不然的话也有可能是录制频道太多导致请求频率在一段时间后超出平台风控限制了？

**Comment by Ju9aad** [comment]
> > 据我的发现是刷新几个违规的直播间会导致后面的刷新一直无法更新
> 
> 这个能确定吗，有尝试过只录制一个正常直播间 + 一个违规直播间的情况吗，不然的话也有可能是录制频道太多导致请求频率在一段时间后超出平台风控限制了？

一个正常的+一个违规的是可以的，五个违规+添加一个正常的直播间，这时已经无法添加成功了，而且一直刷新
![微信截图_20231209113515](https://github.com/WhiteMinds/LiveAutoRecord/assets/97628900/e44ca54c-c40d-4dbc-814e-6cac40d70bd9)

**Comment by WhiteMinds** [comment]
> 一个正常的+一个违规的是可以的，五个违规+添加一个正常的直播间，这时已经无法添加成功了，而且一直刷新

看起来确实像是被风控给 ban 了，你可以试试在这种情况下，从浏览器访问，应该也会无法访问？或者还要分登录下和非登录下访问。

**Comment by Ju9aad** [comment]
> > 一个正常的+一个违规的是可以的，五个违规+添加一个正常的直播间，这时已经无法添加成功了，而且一直刷新
> 
> 看起来确实像是被风控给 ban 了，你可以试试在这种情况下，从浏览器访问，应该也会无法访问？或者还要分登录下和非登录下访问。

浏览器的话一直可以的

**Comment by WhiteMinds** [comment]
> 浏览器的话一直可以的

不太可能，软件走的和浏览器应该是同一个接口，浏览器未登录状态有测试吗

**Comment by Ju9aad** [comment]
> 给 ban 了，你可以试试在这种情况下，从浏览

没有在没登录的情况下试过，全程登录，现在也不好复现了，没那么多要录的主播了，还有一个非常严重的问题，我录了一个抖音的女主播【ETC.】它在本地也生成这个名字的文件夹，结果是无法录入数据，这个文件件我想了好多办法也删除不掉，双击就显示
![微信截图_20231216184526](https://github.com/WhiteMinds/LiveAutoRecord/assets/97628900/bcf0311e-5648-4027-80ac-3da733579b52)
帮忙瞅瞅这个是什么问题，谢谢大佬

**Comment by Ju9aad** [comment]
> > 没有在没登录的情况下试过，全程登录，现在也不好复现了，没那么多要录的主播了，还有一个非常严重的问题，我录了一个抖音的女主播【ETC.】它在本地也生成这个名字的文件夹，结果是无法录入数据，这个文件件我想了好多办法也删除不掉，双击就显示 ![微信截图_20231216184526](https://private-user-images.githubusercontent.com/97628900/290987302-bcf0311e-5648-4027-80ac-3da733579b52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODIzODQsIm5iZiI6MTcwMjg4MjA4NCwicGF0aCI6Ii85NzYyODkwMC8yOTA5ODczMDItYmNmMDMxMWUtNTY0OC00MDI3LTgwYWMtM2RhNzMzNTc5YjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA2NDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZGFmYTQ4NjU3YjE3YjcxY2U2MjhjOWRmYzZlMGY1MzAxYTdlMzIxOGNmNzI5MDUzZWVlMmMwN2EwMzA0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_KPCCNtZ5hYobGrXiVDug-IqM_qTBNeJ8IMbE7xrgQ) 帮忙瞅瞅这个是什么问题，谢谢大佬
> 
> 这个问题和 #126 有点像，但正常情况下它应该创建文件夹失败，这里则是因为 nodejs 绕过了 windows 默认的文件夹命名限制，创建了以 `.` 结尾的文件夹。
> 
> 普通情况下 windows GUI 操作和 windows 命令是会忽略文件夹中结尾的 `.` 的，你可以参考这里的方案来解决：https://stackoverflow.com/a/4123173

谢谢大佬，salute！

**Comment by WhiteMinds** [comment]
这个问题之后在 #102 中跟踪
