### ISSUE TITLE
今天不能录斗鱼了，用其他软件还可以，是否斗鱼有改版？

### ISSUE THREAD

**Issue by lededev** [WhiteMinds/LiveAutoRecord#138]
如题，报个bug

**Comment by WhiteMinds** [comment]
我这里测试看起来正常，你那是所有斗鱼直播间还是少数几个无法录制了？

有没有测试过在非登录状态下的网页端访问直播间看看是否正常？是不是 ip 被 ban 了？

**Comment by lededev** [comment]
昨晚20:30就不能录这个斗鱼直播间了，https://www.douyu.com/topic/ysjsxh?rid=4238637&dyshid=1baf82cf-519c3a150f4ce6edd722ff2300041601
从网页进去或者app进去是开播着的，也没有被封ip，用这个软件就一直开始、停止，只留下一堆.json。
别的直播间我没试，

**Comment by lededev** [comment]
这两天又能录了，由于问题无法重现，我先关掉这个issue了。

**Comment by lededev** [comment]
找到原因了，是网络而不是软件问题。
录制流的URL并不总是包含斗鱼域名的网址，当这个流网址以非斗鱼.com结尾时，不被域名数据库识别为国内域名，走了外网的流量，因此被斗鱼识别为境外访问，而被频繁断开。
将这个域名在路由器设置为走国内直连或者走国内代理，录制就恢复正常了。
