### ISSUE TITLE
虎牙报错403

### ISSUE THREAD

**Issue by CHDKBL** [WhiteMinds/LiveAutoRecord#139]
[2023-12-28 17-15-44 5点现金杯！.ffmpeg.log](https://github.com/WhiteMinds/LiveAutoRecord/files/13785025/2023-12-28.17-15-44.5.ffmpeg.log)
使用的是4.3.4版本，系统win10。

**Comment by WhiteMinds** [comment]
是所有直播间都这样还是单个直播间，会不会是本机的 ip 被 ban 了？现在录制正常吗？

**Comment by BelieveDa** [comment]
> 是所有直播间都这样还是单个直播间，会不会是本机的 ip 被 ban 了？现在录制正常吗？

对的 虎牙的所有都是这个问题

**Comment by WhiteMinds** [comment]
确实可以复现，我用的是 https://github.com/wbt5/real-url 中的流地址获取方案，看起来这个方案现在有些问题 https://github.com/wbt5/real-url/issues/465

**Comment by FreeTymeKiyan** [comment]
有问题 好几天都403

**Comment by FreeTymeKiyan** [comment]
@WhiteMinds 能修吗？还是必须得等着real-url更新？

有的别的软件已经修好了

**Comment by WhiteMinds** [comment]
> @WhiteMinds 能修吗？还是必须得等着real-url更新？

应该能吧，不等 real-url 更新，但是要等我有空看

> 有的别的软件已经修好了

有能用的就没必要催我这个吧。。

**Comment by WhiteMinds** [comment]
HuyaRecorder 的包我先修复发布了 https://github.com/WhiteMinds/HuYaRecorder/commit/957d2d6441d72c1af023c296d096d98c3fbec54e

LAR 这里的等过两天我连着其他的一些功能一起发布

**Comment by WhiteMinds** [comment]
在 4.3.5 中修复了该问题 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.3.5
