### ISSUE TITLE
生成的SRT弹幕文件都是0字节，没有任何内容

### ISSUE THREAD

**Issue by hsk110120119** [WhiteMinds/LiveAutoRecord#141]
安装使用的是@autorecord.electron-setup-4.3.4.exe
录像等都正常，就是生成的SRT弹幕文件没有内容，大小为0字节。
不知是BUG还是自己在设置上有什么问题？

**Comment by hsk110120119** [comment]
忘了说录制的是抖音，其他的还没试过

**Comment by WhiteMinds** [comment]
抖音目前不支持弹幕录制

**Comment by WhiteMinds** [comment]
该问题之后在 #179 中跟踪。
