### ISSUE TITLE
能不能把禁用自动录制的状态显示在主页

### ISSUE THREAD

**Issue by 948720857** [WhiteMinds/LiveAutoRecord#150]
添加显示自动录制是否开启

**Comment by WhiteMinds** [comment]
在新版本中添加了
https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.4.0

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/1b4613c1-b83e-4be8-8c33-bd8df4f42020)
