### ISSUE TITLE
挂在电脑上录制一个晚上 第二天会发现所有添加的主播都获取不到开播信息无法录制，重新打开软件会提示错误

### ISSUE THREAD

**Issue by Visper01** [WhiteMinds/LiveAutoRecord#152]
![PixPin_2024-01-31_12-21-02](https://github.com/WhiteMinds/LiveAutoRecord/assets/68221878/6e650628-9dde-4317-b7d7-c3b98cedd145)

**Comment by WhiteMinds** [comment]
看提示的意思是，LAR 准备使用的 8085 端口被占用了，有两种可能：

1. 电脑上有旧的 LAR 进程没有被销毁并且没被识别出来，因为如果识别出来了会自动弹出来
2. 电脑上有其他进程占用了 8085 端口，我猜这个可能性大一些，你需要查一下是谁占用的

**Comment by Visper01** [comment]
好的 经过尝试之后错误提示已经解决了 但是添加过的主播就算开播也不会录制 点击刷新会一直转圈，然后我再添加新的录制任务会一直在解析链接，电脑没有开VPN
![微信截图_20240131145653](https://github.com/WhiteMinds/LiveAutoRecord/assets/68221878/891afe21-d766-405e-a495-575f7b444c88)
![微信截图_20240131145617](https://github.com/WhiteMinds/LiveAutoRecord/assets/68221878/3fa7e319-fc7d-487e-b53a-f97a1ed386d3)

**Comment by Visper01** [comment]
好的，经过尝试问题解决了，感谢大佬
