### ISSUE TITLE
怎么加修改格式的命令

### ISSUE THREAD

**Issue by q1518001822** [WhiteMinds/LiveAutoRecord#155]
就是录时候lfv 输出后转换成mp4  这个命令怎么写

**Comment by WhiteMinds** [comment]
只能直接录成 flv 或者 mp4，如果要录制成 flv，再转成 mp4，需要手动进行

**Comment by 948720857** [comment]
https://github.com/mifi/lossless-cut
用这个可以不用重编码直接转格式
