### ISSUE TITLE
希望在做一下录播文件自动上传b站功能

### ISSUE THREAD

**Issue by q1518001822** [WhiteMinds/LiveAutoRecord#156]
b站已经开放了api接口 目前已经有多个版本自动上传工具 但是有的有局限 有的上手难度大 希望开发win系统环境的应用并支持斗鱼录播的自动上传

**Comment by WhiteMinds** [comment]
这个不考虑，因为 LAR 主要是作为一个录制和回放的工具，多平台的自动上传支持起来也比较麻烦，应该由专门的自动上传的工具来处理。
