### ISSUE TITLE
录制的视频文件都损坏了，无法打开

### ISSUE THREAD

**Issue by kidkid678** [WhiteMinds/LiveAutoRecord#159]
是因为没有将安装到c盘的缘故吗？

**Comment by WhiteMinds** [comment]
损坏的具体表现是什么样？无法播放？文件大小为 0？

安装位置理论上是无影响的，但是录制保存路径和命名规则需要确保配置正确。

**Comment by kidkid678** [comment]
> 损坏的具体表现是什么样？无法播放？文件大小为 0？
> 
> 安装位置理论上是无影响的，但是录制保存路径和命名规则需要确保配置正确。

potplayer显示该媒体无法播放，该文件目前无法解析影音播放问题，刚刚试了一下，录制时间长一些就可以正常播放了，但是仅仅录制一分钟以内就会出现问题

**Comment by WhiteMinds** [comment]
> 但是仅仅录制一分钟以内就会出现问题

噢是的，因为软件默认配置的参数是按照 fmp4 格式录制并且设置的片段时间是 1 分钟，所以每隔一分钟才写入一次文件。
