### ISSUE TITLE
录制抖音直播添加直播间问题

### ISSUE THREAD

**Issue by fgo1212** [WhiteMinds/LiveAutoRecord#162]
抖音没直播怎么添加直播间？我添加 https://live.douyin.com/主页抖音号 解析出直播间再添加 但是有的能解析出有的解析不出，这是什么原因？怎么解决？

**Comment by WhiteMinds** [comment]
我记得这个问题修过，你使用的是哪个版本？

**Comment by fgo1212** [comment]
> 我记得这个问题修过，你使用的是哪个版本？

v4.3.5

**Comment by WhiteMinds** [comment]
你有设置什么系统代理之类的吗？我刚刚试了下走代理的时候有些逻辑没处理好会导致请求失败。

如果没有的话，你可以给几个无法解析的直播间地址这样我好复现问题看看。

**Comment by WhiteMinds** [comment]
> 这些我添加都解析不出直播间，你试试看行不行

调试了下知道原因了，过两天修

> 还发现个问题，我测试完上面这几个解析不出直播间的链接后，录制历史和录制设置打开一直转圈刷不出来，要重启才能刷出来

挺奇怪的，这个应该不会影响到，我本地也无法复现出这个问题

**Comment by fgo1212** [comment]
> 还发现个问题，我测试完上面这几个解析不出直播间的链接后，录制历史和录制设置打开一直转圈刷不出来，要重启才能刷出来

那可能录制历史和录制设置打开一直转圈刷不出来可能不是因为我测试解析链接，反正有录制历史和录制设置打开一直转圈刷不出来要重启软件才恢复的问题，我也不知道怎么复现

**Comment by WhiteMinds** [comment]
部分抖音直播间无法添加的问题在新版本中已修复：
https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.4.0
