### ISSUE TITLE
内置播放器和录制历史问题

### ISSUE THREAD

**Issue by fgo1212** [WhiteMinds/LiveAutoRecord#167]
试了下内置播放器，可以支持弹幕很不错，不过貌似没有2倍速快捷键不太方便，而且也不能记住倍速，也不能自动播放下一个视频，而且也不会显示播放视频标题，经常搞不清楚是到底播放到哪个视频了，使用起来不太方便

录制历史建议增加一个筛选选项，不然太乱了找想找的主播很难，还有把文件删除了录制历史里却还在，而且录制历史也没有清除选项，管理不太方便，还有播放过的记录能不能增加个标记，不然也很难搞清楚看到哪个了

**Comment by WhiteMinds** [comment]
> 不过貌似没有2倍速快捷键不太方便，而且也不能记住倍速

https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.4.0 在新版本中加了两个快捷键 `[` 和 `]` 来调节倍速。

> 也不能自动播放下一个视频

这个暂时不打算做。

> 而且也不会显示播放视频标题

在新版本中加了。

> 录制历史建议增加一个筛选选项

在新版本中加了。

> 还有把文件删除了录制历史里却还在，而且录制历史也没有清除选项

新版本加了一个清理无效记录的功能，并且对文件已被删除的记录会禁用操作按钮来突出显示。

> 播放过的记录能不能增加个标记

这个暂时不打算做。

**Comment by WhiteMinds** [comment]
想了下，那两个功能我先建对应的 issues 去跟踪，但什么时候开始做不知道。

1. #183
2. #184
