### ISSUE TITLE
放录播的视频轮播也会自动录制，能不能加个功能识别下只录直播？

### ISSUE THREAD

**Issue by fgo1212** [WhiteMinds/LiveAutoRecord#173]
放录播的视频轮播也会自动录制，能不能加个功能识别下只录直播？

**Comment by WhiteMinds** [comment]
是斗鱼的吗？

**Comment by fgo1212** [comment]
> 是斗鱼的直播间吗？

是的

**Comment by WhiteMinds** [comment]
> > 是斗鱼的直播间吗？
> 
> 是的

这个之前是有处理过的，我刚刚测试了下，斗鱼的轮播是不会录制的，你是不是把主播自己放的视频直播看成轮播了？

**Comment by fgo1212** [comment]
> > > 是斗鱼的直播间吗？
> > 
> > 
> > 是的
> 
> 这个之前是有处理过的，我刚刚测试了下，斗鱼的轮播是不会录制的，你是不是把主播自己放的视频直播看成轮播了？

我用最新版测试了下，主播下播后会继续录制录播，不会自动停止，要手动停止后才不会录制录播，测试直播间https://www.douyu.com/290935，建议增加个识别录播自动停止录制功能

**Comment by WhiteMinds** [comment]
> 主播下播后会继续录制录播，不会自动停止

听起来像是主播没有终止推流。不过这种平台应该会有限制，下播一段时间后还在推流应该会强制断掉。

> 你测试下，我不知道他是不是自己放的视频，反正右上角显示录像

我现在访问看是直播状态的，你下次截图下。

平台自己的轮播是比较明显的：

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/8d1650a2-a9e9-4542-8a5a-4eec8baf7968)

**Comment by fgo1212** [comment]
> > 主播下播后会继续录制录播，不会自动停止
> 
> 听起来像是主播没有终止推流。不过这种平台应该会有限制，下播一段时间后还在推流应该会强制断掉。
> 
> > 你测试下，我不知道他是不是自己放的视频，反正右上角显示录像
> 
> 我现在访问看是直播状态的，你下次截图下。
> 
> 平台自己的轮播是比较明显的：
> 
> ![image](https://private-user-images.githubusercontent.com/9160743/322272467-8d1650a2-a9e9-4542-8a5a-4eec8baf7968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjU5NzYsIm5iZiI6MTcxMzE2NTY3NiwicGF0aCI6Ii85MTYwNzQzLzMyMjI3MjQ2Ny04ZDE2NTBhMi1hOWU5LTQ1NDItOGE1YS00ZWVjOGJhZjc5NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDcyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE2YjRhZTFlMGRlZTlmMTE1MjU1Zjc1ZmU3MGUyNzc4M2MyODZlZTZjNjQ3OGM4ZTE3ZWY3OWUxMzlmMjQ2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.35JwjSlzGApCSS4aLOfnF7zv3yAKtf6zueKMJgTsAEU)

和你的截图一样
![QQ截图20240415152809](https://github.com/WhiteMinds/LiveAutoRecord/assets/96370506/a62bc817-aae1-473d-a584-e374b16b30cb)

**Comment by WhiteMinds** [comment]
> 和你的截图一样

这个时候软件会开始录制吗，如果在录制的话终止之后还会再录吗？

我现在去看这个直播间还是直播中，所以没法直接测试，我之前是用其他直播间测试看轮播是不录的。

**Comment by WhiteMinds** [comment]
我好像复现出这个问题了，等之后有空的时候调查下原因。

我估计是下播之后直接开始轮播的原因，可能那个时候网站打上视频轮播的标记有延迟，但是轮播的流已经推了。

**Comment by WhiteMinds** [comment]
在 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.7.1 中修复了
