### ISSUE TITLE
录制的视频时长若小于60s就无法播放

### ISSUE THREAD

**Issue by HanXiuHenry** [WhiteMinds/LiveAutoRecord#176]
录制的视频时长若小于60s就无法播放

**Comment by AvrilL161** [comment]
In the settings change the interval (in microseconds)
![2024-03-04_19-44-15](https://github.com/WhiteMinds/LiveAutoRecord/assets/29428522/1e7d9db4-2c3f-458d-bad4-a10f50df8aac)

**Comment by WhiteMinds** [comment]
这是默认的 ffmpeg 输出参数中所配置的，默认是 fmp4，每 60s 作为一个 fragment 保存一次。
