### ISSUE TITLE
发现录制斗鱼直播有会漏录半个小时左右内容的问题

### ISSUE THREAD

**Issue by fgo1212** [WhiteMinds/LiveAutoRecord#181]
发现录制斗鱼直播有会漏录半个小时左右内容的问题

**Comment by WhiteMinds** [comment]
应该和 #177 是同一个问题，是不是漏录的同时自动终止也失效了？就是一直显示在录制中但是没有录内容。

**Comment by fgo1212** [comment]
> 打开调试模式等下一次复现问题了再传下日志。

不清楚，是后来看录像的时候发现的，我打开调试模式了，要是发现复现问题了再传下日志。

**Comment by WhiteMinds** [comment]
在新版本中对这个问题做了尝试性的修复 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.6.1

这个 issue 我就先关掉了，如果新版本中仍然遇到这个问题，可以重新打开这个 issue 或新建一个。
