### ISSUE TITLE
支持 I18N

### ISSUE THREAD

**Issue by WhiteMinds** [WhiteMinds/LiveAutoRecord#182]
暂定新增 English 和 Russian。

**Comment by AvrilL161** [comment]
> 暂定新增 English 和 Russian。

The inscriptions in Chinese are much shorter than in English and Russian. You may have to rework the interface and replace some labels with icons.
But if you decide to adapt it to other languages, then I will help with the translation.

**Comment by WhiteMinds** [comment]
在新版本中 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.5.0 新增了 English 和 Russian 的国际化支持。

**Comment by WhiteMinds** [comment]
> But if you decide to adapt it to other languages, then I will help with the translation.

I used AI for automatic translation, there may be errors.

If you find any mistakes in the translation, you can create a PR or open a new issue to address it.
