### ISSUE TITLE
有几点问题，关于录制设置的，还有提一点建议

### ISSUE THREAD

**Issue by Pikarziur** [WhiteMinds/LiveAutoRecord#189]
1.录制不到1分钟，视频无法播放（应该是大约1分钟吧，具体多少秒不太清楚）
2.主播首次添加时，录制画质我选择了最高，因为首次添加无法选择视频流和视频源，发现录制的视频只有480p，后续手动选择了原画视频流，问题依旧

建议：
1.可以添加一个实时更新的录制时长？

**Comment by menheng** [comment]
这个问题是登陆限制，建议作者加个登录

**Comment by WhiteMinds** [comment]
> 1.录制不到1分钟，视频无法播放（应该是大约1分钟吧，具体多少秒不太清楚）

因为默认的 FFMPEG 输出参数设置的是 `-c copy -movflags frag_keyframe -min_frag_duration 60000000`，每 60 秒分段写入一次，可以自行调整。

> 2.主播首次添加时，录制画质我选择了最高，因为首次添加无法选择视频流和视频源，发现录制的视频只有480p，后续手动选择了原画视频流，问题依旧

哪个平台，是特定平台有这个问题还是特定平台的特定直播间有这个问题？

> 1.可以添加一个实时更新的录制时长？

考虑到网络波动可能会导致录制多次的终止和重新开始，那么这个时间的意义就不大了，所以暂时不考虑这个需求。

**Comment by Pikarziur** [comment]
我只尝试过B站的，连续试了几个直播间都是输出480p

**Comment by WhiteMinds** [comment]
> 我只尝试过B站的，连续试了几个直播间都是输出480p

看了下确实有这个问题我这里可以复现，等之后有空的时候修下。
