### ISSUE TITLE
死机或崩溃等导致软件瞬间关闭的情况可能导致软件白屏，重启、卸载重装依旧

### ISSUE THREAD

**Issue by menheng** [WhiteMinds/LiveAutoRecord#193]

**Comment by menheng** [comment]
{"label":"default","level":"error","message":"unhandledRejection Unexpected token '\u0000', \"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"... is not valid JSON","stack":"SyntaxError: Unexpected token '\u0000', \"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at JSONFile.read (E:\\LAR 直播自动录制\\@autorecordelectron\\resources\\app.asar\\node_modules\\@autorecord\\http-server\\lib\\db\\lowdb.js:46:25)\n    at async Low.read (E:\\LAR 直播自动录制\\@autorecordelectron\\resources\\app.asar\\node_modules\\@autorecord\\http-server\\lib\\db\\lowdb.js:26:21)\n    at async initDB (E:\\LAR 直播自动录制\\@autorecordelectron\\resources\\app.asar\\node_modules\\@autorecord\\http-server\\lib\\db\\index.js:15:5)\n    at async Object.startServer (E:\\LAR 直播自动录制\\@autorecordelectron\\resources\\app.asar\\node_modules\\@autorecord\\http-server\\lib\\index.js:42:5)","timestamp":"2024-03-14T02:13:45.206Z"}
这个是最后一次，白屏发生后的没有

**Comment by WhiteMinds** [comment]
从错误日志来看是数据文件损坏了，你可以删了它再启动软件，它的位置是 `%LOCALAPPDATA%\live-auto-record\Data\data.json`。

但比较奇怪的是，这个数据文件应该有防止写入中断导致文件损坏的措施，不知道你那里是咋损坏的。

**Comment by OriX0** [comment]
> 从错误日志来看是数据文件损坏了，你可以删了它再启动软件，它的位置是 `%LOCALAPPDATA%\live-auto-record\Data\data.json`。
> 
> 但比较奇怪的是，这个数据文件应该有防止写入中断导致文件损坏的措施，不知道你那里是咋损坏的。

可能是主播的名字中带有表情，导致parse出错

**Comment by bohscs** [comment]
我这里死机崩溃重启电脑再打开软件也是空白 那个文件也损坏

**Comment by WhiteMinds** [comment]
在新版本中会自动忽略损坏的数据文件而不是出现白屏：https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.7.0

数据损坏的原因不明，之后如果在新版本中复现了再开个 issue 吧，这个先关闭了。
