### ISSUE TITLE
录制抖音直播时， 不断重新开始录制

### ISSUE THREAD

**Issue by JOJOforshaun** [WhiteMinds/LiveAutoRecord#199]
每次 只能录制几秒钟，然后重新开始录制
<img width="1136" alt="截屏2024-03-24 22 41 04" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/63553362/871d3ee9-abe3-4970-9f42-3fe6dafb4c01">
<img width="1136" alt="截屏2024-03-24 22 41 15" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/63553362/3e573b3c-db70-4c70-80f4-891d0146c26c">

**Comment by vritser** [comment]
我也遇到这个问题了

**Comment by vritser** [comment]
调整ffmpeg超时时间后正常

**Comment by WhiteMinds** [comment]
> 调整ffmpeg超时时间后正常

你是调了软件内的 10 秒超时时间？还是调了 probesize / analyzeduration？或者其他参数？

目前我降低 probesize 之后可以正常，但是不确定这么操作是否合理。

**Comment by WhiteMinds** [comment]
新版本中尝试解决了这个问题 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.7.0

目前的解决思路是这样：https://github.com/WhiteMinds/DouYinRecorder/blob/master/src/index.ts#L122-L131

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/ecdf6555-83d9-4997-9e34-e0bd9ed0c9e8)
