### ISSUE TITLE
录制不了，解析不了，也设置不了，设置一直在转圈

### ISSUE THREAD

**Issue by 1sgfg** [WhiteMinds/LiveAutoRecord#200]
V4.3.5版本的，
卸载后重新装机也不行，就一直转圈圈，解析，设置都是，录制全局设置和应用设置都一直转圈
这个状况是突然就这样的，一直都能正常录制，突然就不行了，添加的录制的也全被清楚掉了，卸载重新装也不行，系统是WIN11

**Comment by WhiteMinds** [comment]
应该是 #88 这个问题，参考里面的解决方案。

另外这个问题之后会在 #193 追踪。
