### ISSUE TITLE
希望增加支持网易CC直播的录制！

### ISSUE THREAD

**Issue by alaaflu** [WhiteMinds/LiveAutoRecord#208]
希望增加支持网易CC直播的录制，谢谢！！
目前CC直播有IP分控，如能开发支持网易CC直播的录制，建议模拟CC直播APP获取主播开播状态和直播流，目前使用bililive-go进行录制时每30分钟后就会触发IP风控：同网络环境网页就无法打开，录制就会不正常，但是APP可以正常访问。

**Comment by WhiteMinds** [comment]
Dup #207
