### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by q1518001822** [WhiteMinds/LiveAutoRecord#209]
每次开始录制 分段录前几秒都卡画面  时间长中间也会卡 半年一直没解决 别的软件都正常稳定录就不是网络问题

**Comment by q1518001822** [comment]
蓝光4M 15帧  有点搞笑

**Comment by q1518001822** [comment]
原画30帧

**Comment by WhiteMinds** [comment]
> 每次开始录制 分段录前几秒都卡画面 时间长中间也会卡 半年一直没解决 别的软件都正常稳定录就不是网络问题

卡画面具体是什么意思？太模糊了，这句话的含义有非常多种解释的方式。

听着和网络应该没什么关系，这里提一下网络是为啥，是有哪方面的猜测吗？可以讲的详细一些。

> 半年一直没解决

这个我不能保证在什么时间解决，也不能保证未来一定能解决，毕竟我现在只是偶尔有时间才能维护下。甚至以后某段时间停止维护也是可能的。

> 蓝光4M 15帧 有点搞笑
> 原画30帧

这两个回复和这个问题有什么关联吗？没太理解，是直播平台提供的帧率和录下来的对不上？

**Comment by q1518001822** [comment]
帧率放一边你就先把开始录制或者开始录下一段开始时画面卡顿 问题解决一下 先满足基本的能用水平再说

**Comment by q1518001822** [comment]
斗鱼平台

**Comment by WhiteMinds** [comment]
你还是没有说清楚卡顿到底是什么意思，在发出评论前可以换位思考下别人在缺少专属于你的上下文信息时阅读你的评论是否能理解。

否则这样一来一回就比较浪费时间，这个问题目前只有你一个人反馈，所以如果你不能提供有帮助的反馈信息的话，我就无法开始处理。

另外如果到时候排查发现处理比较麻烦，也可能会往后推迟处理，因为没收到其他的反馈。

**Comment by q1518001822** [comment]
确实只有我 别人都不用 这么明显自己做的东西自己不去试
