### ISSUE TITLE
主播昵称以 `.` 符号结尾时无法正常录制，生成的路径不正确

### ISSUE THREAD

**Issue by xiaoxin122** [WhiteMinds/LiveAutoRecord#211]
抖音作者昵称符号  .   结尾，生成的文件夹错误，录制自动中断，报错 ffmpeg exited with code 1 ，No such file or directory

**Comment by WhiteMinds** [comment]
是最新的 4.7.0 版本吗？这个版本应该有个路径处理的功能的。

**Comment by xiaoxin122** [comment]
> 是最新的 4.7.0 版本吗？这个版本应该有个路径处理的功能的。

是这个版本，作者昵称的路径\{owner}\，添加东西就可以了吗

**Comment by WhiteMinds** [comment]
噢我想起来了，这个路径处理是不处理 `.` 字符的，因为 win 并不禁止这个符号，你那个录制出错的生成的路径是啥样的？找不到的话看看那个抖音昵称是啥？

**Comment by xiaoxin122** [comment]
> 噢我想起来了，这个路径处理是不处理 字符的，因为 win 并不禁止这个符号，你那个录制出错的生成的路径是啥样的？找不到的话看看那个抖音昵称是啥？`.`

生成的路径就是作者昵称，然后作者的昵称是符号 . 结尾，录制会自动中断报错。

现在解决了，设置里面，把路径规则，owner替换成remarks就可以了，用备注的名字保存路径

**Comment by WhiteMinds** [comment]
> 然后作者的昵称是符号 . 结尾

windows 不支持以空格或者 . 结尾的路径，我之后再改一下那个路径处理的功能。

**Comment by WhiteMinds** [comment]
在 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.7.1 中修复了
