### ISSUE TITLE
我想更换电脑安装软件，怎么导入我之前添加的录制作者信息

### ISSUE THREAD

**Issue by 897601689** [WhiteMinds/LiveAutoRecord#212]
请问一下 换了电脑重新安装了软件，如何导入之前添加的录制信息，添加的录制信息保存在什么路径中了

**Comment by WhiteMinds** [comment]
Windows 系统的话配置文件在这几个地方：
频道配置文件 %LOCALAPPDATA%\live-auto-record\Data\data.json
全局录制配置文件 %APPDATA%\live-auto-record\Config\manager.json
应用配置文件 %APPDATA%\live-auto-record\Config\settings.json
