### ISSUE TITLE
更新新版本后，自动录制失灵

### ISSUE THREAD

**Issue by wqjrrrucdk** [WhiteMinds/LiveAutoRecord#215]
更新新版本后，自动录制失灵
刚打开的时候是好用的，运行一两小时后，就不自动录制了。
很是困扰，要等我看到开播后，重启软件或者手动刷新才能开始录

**Comment by WhiteMinds** [comment]
新版本是 4.7.1 吗？

录制哪个直播平台？录制多少个直播间？

**Comment by wqjrrrucdk** [comment]
抖音，19个直播间

**Comment by WhiteMinds** [comment]
#102 这个问题，把检测频率调低

**Comment by wqjrrrucdk** [comment]
我后来又做测试了，需要把原来版本的配置文件和DATE都删除，再安装新的版本，就正常了。
