### ISSUE TITLE
录制后文件夹删除不了

### ISSUE THREAD

**Issue by main-key** [WhiteMinds/LiveAutoRecord#216]
![Mi_20240430_110449](https://github.com/WhiteMinds/LiveAutoRecord/assets/64778656/94e2b01a-769f-46a3-a702-80419e148b1d)
录制后文件夹删除不了

**Comment by WhiteMinds** [comment]
是这个问题 https://github.com/WhiteMinds/LiveAutoRecord/issues/136#issuecomment-1859657413

然后在最新版中有处理 https://github.com/WhiteMinds/LiveAutoRecord/issues/211#issuecomment-2058692699
