### ISSUE TITLE
抖音录像加载不出

### ISSUE THREAD

**Issue by 7621ru** [WhiteMinds/LiveAutoRecord#224]
一直用了估计2个月了，是4.7.0下载4.7.1下载不了，之前一直特别好用，昨天晚上看回放，3个小时的加载不出，就不能用了，怎么回事阿，大佬，急急急，呜呜呜

**Comment by 7621ru** [comment]
找到问题了，是硬盘坏了，之前的视频也不能看了，感谢大佬研究的软件，感谢..

**Comment by WhiteMinds** [comment]
amazing
