### ISSUE TITLE
刚用了一天就用不了了

### ISSUE THREAD

**Issue by hxinchen** [WhiteMinds/LiveAutoRecord#231]
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/78190391/d487c625-d082-4cbd-af55-a4e7c1ce7f20)
软件一直开着，刚开始用还是能用的，自动录屏什么的都正常，后来就没法用了，主播开播了也没有自动录屏，点击刷新一直转圈

**Comment by AvrilL161** [comment]
I had the same problem. But after 2-3 days of continuous use. Now I just reboot LAR once a day through the task scheduler.

**Comment by WhiteMinds** [comment]
是抖音吗？这听起来像是这个问题 #102

**Comment by hxinchen** [comment]
是抖音，我现在就之监听3-4个直播间，所以解决方案 是把检查间隔调大吗，还是说改那个ffmpeg参数

**Comment by WhiteMinds** [comment]
> 是抖音，我现在就之监听3-4个直播间，所以解决方案 是把检查间隔调大吗，还是说改那个ffmpeg参数

对，调大检查间隔，调参数没什么效果
