### ISSUE TITLE
您好，请问windows下如何使用，可以有一个简单的步骤嘛，需要安装哪一些依赖包。

### ISSUE THREAD

**Issue by xiatiantiantian** [WhiteMinds/LiveAutoRecord#4]
想使用，但不太会弄。

**Comment by xiatiantiantian** [comment]
PS D:\electron-builder\LiveAutoRecord\LiveAutoRecord> yarn dist
yarn run v1.16.0
warning ..\..\package.json: No license field
$ electron-builder
  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=build\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=sqlite3
  • packaging       platform=win32 arch=x64 electron=5.0.1 appOutDir=build\win-unpacked
Error: Application entry file "dist\electron\main.js" in the "D:\electron-builder\LiveAutoRecord\LiveAutoRecord\build\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (D:\electron-builder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:44:14)
    at D:\electron-builder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _checkFileInArchive (D:\electron-builder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:36:17)
    at checkFileInArchive (D:\electron-builder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:40:30)
    at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.checkFileInPackage (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:406:110)
    at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at WinPackager.sanityCheckPackage (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:446:92)
    at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (D:\electron-builder\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\electron-builder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:396:24)
    at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at D:\electron-builder\node_modules\graceful-fs\graceful-fs.js:111:16
    at D:\electron-builder\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:335:133)
    at D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\electron-builder\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (D:\electron-builder\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (D:\electron-builder\node_modules\electron-builder\src\builder.ts:228:10)
    at then (D:\electron-builder\node_modules\electron-builder\src\cli\cli.ts:49:19)
error Command failed with exit code 1.

**Comment by WhiteMinds** [comment]
README.md中有写, 如果你想跑起开发环境, 那么
`# install dependencies
yarn (or 'npm install')
yarn rebuild:sqlite3 (or 'npm run rebuild:sqlite3')

# serve with hot reload at localhost:9080
yarn dev (or 'npm run dev')`

**Comment by xiatiantiantian** [comment]
> README.md中有写, 如果你想跑起开发环境, 那么
> 
> ```
> // install dependencies
> yarn (or 'npm install')
> yarn rebuild:sqlite3 (or 'npm run rebuild:sqlite3')
> 
> // serve with hot reload at localhost:9080
> yarn dev (or 'npm run dev')
> ```

嗯，我yarn dev 可以运行调试，打开界面使用。
但是我用electron-builder （版本号20.44.1）  yarn build生成的文件是无法打开的。
点击EXE提示：
 ReferenceError: __static is not defined
at App.r (D:\electron-builder\LiveAutoRecord\LiveAutoRecord\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:22899)
at App.emit (events.js:199:15)


![2222](https://user-images.githubusercontent.com/51699978/59588516-599ab880-911a-11e9-8b90-1f154f2e0709.png)

**Comment by xiatiantiantian** [comment]
> README.md中有写, 如果你想跑起开发环境, 那么
> 
> ```
> // install dependencies
> yarn (or 'npm install')
> yarn rebuild:sqlite3 (or 'npm run rebuild:sqlite3')
> 
> // serve with hot reload at localhost:9080
> yarn dev (or 'npm run dev')
> ```

嗯，我yarn dev 可以运行调试，打开界面使用。
但是我用electron-builder （版本号20.44.1） yarn build生成的文件是无法打开的。
点击EXE提示：
ReferenceError: __static is not defined
at App.r (D:\electron-builder\LiveAutoRecord\LiveAutoRecord\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:22899)
at App.emit (events.js:199:15)

![2222](https://user-images.githubusercontent.com/51699978/59588655-af6f6080-911a-11e9-9374-ced43c4b3a90.png)

**Comment by WhiteMinds** [comment]
呃, 好像是我还没push完改动, 因为我本地还有一堆功能在做, 没有实时push, 你等下一次commit吧...

**Comment by xiatiantiantian** [comment]
> 呃, 好像是我还没push完改动, 因为我本地还有一堆功能在做, 没有实时push, 你等下一次commit吧...

好的，辛苦了。
1.我试了试，目前这个版本，我点了停止录制，但是会再次自动录制。

2.可否在 生成文件的名字 里面增加一个 直播间标题 的选项，列如 （时间+主播名字+标题.flv）

3. 可否生成录制文件夹方便查阅，比如这样

 平台名字（文件夹）-- 主播名字（子文件夹）---录制的文件.flv

**Comment by WhiteMinds** [comment]
> > 呃, 好像是我还没push完改动, 因为我本地还有一堆功能在做, 没有实时push, 你等下一次commit吧...
> 
> 好的，辛苦了。
> 1.我试了试，目前这个版本，我点了停止录制，但是会再次自动录制。
> 
> 2.可否在 生成文件的名字 里面增加一个 直播间标题 的选项，列如 （时间+主播名字+标题.flv）
> 
> 1. 可否生成录制文件夹方便查阅，比如这样
> 
> 平台名字（文件夹）-- 主播名字（子文件夹）---录制的文件.flv

1.终止录制后有10秒的不检查时间, 暂时停止所有检查功能在需求中但还未制作
2.在需求列表中
3.该功能已经完成, 可能是你换录制路径的时候没注意, 那里是允许使用变量的, 目前支持的变量有platform, address, 几个时间

**Comment by WhiteMinds** [comment]
你现在pull下最新的代码, 然后build试试?

**Comment by xiatiantiantian** [comment]
> 你现在pull下最新的代码, 然后build试试?

我yarn dev 程序是空百的界面，只有一个左上角的标题。 无法build

**Comment by xiatiantiantian** [comment]
![22222222222](https://user-images.githubusercontent.com/51699978/59965659-cdd2c300-9543-11e9-9440-9854a0937b11.png)

**Comment by xiatiantiantian** [comment]
可以build ，运行exe文件和yarn dev 一样，如上截图  空白界面。只有软件标题。

**Comment by WhiteMinds** [comment]
那么yarn dev时是否有错误报告?

**Comment by xiatiantiantian** [comment]
> 那么yarn dev时是否有错误报告?

┏ Main Process ---------------

  compiling...

┗ ----------------------------

┏ Main Process ---------------

  Hash: 663bc39f57fb8575aa3a
  Version: webpack 4.32.2
  Time: 13600ms
  Built at: 2019-06-23 10:08:29 AM
    Asset     Size  Chunks             Chunk Names
  main.js  336 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/babel-runtime/core-js/promise.js] 88 bytes {main} [built]
  [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
  [./package.json] 4.27 KiB {main} [built]
  [./src/const/index.js] 724 bytes {main} [built]
  [./src/main/config.js] 801 bytes {main} [built]
  [./src/main/index.dev.js] 344 bytes {main} [built]
  [./src/main/index.js] 2.36 KiB {main} [built]
  [./src/main/ipc.js] 1.88 KiB {main} [built]
  [./src/main/store.js] 43 bytes {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [electron-better-ipc] external "electron-better-ipc" 42 bytes {main} [built]
  [fs] external "fs" 42 bytes {main} [built]
  [path] external "path" 42 bytes {main} [built]
      + 129 hidden modules

  WARNING in ./node_modules/electron-debug/index.js 81:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

  WARNING in ./node_modules/electron-debug/index.js 84:85-106
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

┗ ----------------------------

┏ Renderer Process -----------

  Hash: da25cf27604ce1f92eeb
  Version: webpack 4.32.2
  Time: 16234ms
  Built at: 2019-06-23 10:08:32 AM
                        Asset       Size    Chunks             Chunk Names
    fonts/ionicons--fonts.ttf    193 KiB            [emitted]
   fonts/ionicons--fonts.woff    193 KiB            [emitted]
  fonts/ionicons--fonts.woff2   80.3 KiB            [emitted]
     imgs/ionicons--fonts.svg    542 KiB            [emitted]
        imgs/logo--assets.png   16.5 KiB            [emitted]
                   index.html  436 bytes            [emitted]
                  renderer.js   7.11 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [0] multi ./.electron-vue/dev-client ./src/renderer/main.js 40 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 705 bytes {renderer} [built]
  [./node_modules/dplayer/dist/DPlayer.min.css] 940 bytes {renderer} [built]
  [./node_modules/iview/dist/iview.js] 1.55 MiB {renderer} [built]
  [./node_modules/iview/dist/styles/iview.css] 934 bytes {renderer} [built]
  [./node_modules/vue/dist/vue.esm.js] 318 KiB {renderer} [built]
  [./node_modules/webpack-hot-middleware/client.js?noInfo=true&reload=true] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.68 KiB {renderer} [built]
  [./src/renderer/App.vue] 1.12 KiB {renderer} [built]
  [./src/renderer/components/better-table/index.vue] 1.22 KiB {renderer} [built]
  [./src/renderer/components/modal-columns-setting.vue] 1.29 KiB {renderer} [built]
  [./src/renderer/components/vue-rippler.js] 3.72 KiB {renderer} [built]
  [./src/renderer/main.js] 799 bytes {renderer} [built]
  [./src/renderer/modules/store.js] 283 bytes {renderer} [built]
  [./src/renderer/router/index.js] 1.55 KiB {renderer} [built]
  [flv.js] external "flv.js" 42 bytes {renderer} [built]
      + 267 hidden modules

  WARNING in ./node_modules/umzug/lib/helper.js 15:15-22
  Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
   @ ./node_modules/umzug/lib/migration.js
   @ ./src/renderer/db/migrate.js
   @ ./src/renderer/db/index.js
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  WARNING in ./node_modules/umzug/lib/migration.js 81:11-29
  Critical dependency: the request of a dependency is an expression
   @ ./src/renderer/db/migrate.js
   @ ./src/renderer/db/index.js
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  WARNING in ./node_modules/umzug/lib/helper.js 16:15-30
  Critical dependency: the request of a dependency is an expression
   @ ./node_modules/umzug/lib/migration.js
   @ ./src/renderer/db/migrate.js
   @ ./src/renderer/db/index.js
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  WARNING in ./node_modules/umzug/lib/helper.js 19:17-37
  Critical dependency: the request of a dependency is an expression
   @ ./node_modules/umzug/lib/migration.js
   @ ./src/renderer/db/migrate.js
   @ ./src/renderer/db/index.js
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue?vue&type=script&lang=js&
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  WARNING in ./src/renderer/pages/player/index.vue?vue&type=template&id=398d62dc&scoped=true& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/pages/player/index.vue?vue&type=template&id=398d62dc&scoped=true&)
  Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
  (Emitted value instead of an instance of Error) <DropdownItem v-for="val in ChatContentList">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
   @ ./src/renderer/pages/player/index.vue?vue&type=template&id=398d62dc&scoped=true& 1:0-227 1:0-227
   @ ./src/renderer/pages/player/index.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.15 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

┗ ----------------------------

**Comment by WhiteMinds** [comment]
你进群634509226, 群里聊吧
