### ISSUE TITLE
dm3弹幕文件怎么用？

### ISSUE THREAD

**Issue by fgo1212** [WhiteMinds/LiveAutoRecord#44]
用软件里播放器播放显示不了弹幕，有别的播放器能播放dm3弹幕文件吗？

**Comment by WhiteMinds** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    其他播放器无法直接使用 dm3，软件里播放器显示不了，可能是因为确实没有录制到弹幕
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                whitemind
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2022年06月6日 ***@***.***> 写道： 




用软件里播放器播放显示不了弹幕，有别的播放器能播放dm3弹幕文件吗？



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by WhiteMinds** [comment]
4.x 取消 dm3 文件了，改成 json 了
