### ISSUE TITLE
软件很好，但是弹幕功能用不了

### ISSUE THREAD

**Issue by zxy1206** [WhiteMinds/LiveAutoRecord#48]
想尝试做斗鱼的弹幕版录播，这个软件是最方便的选择，但是弹幕功能没办法使用，回放里看不到弹幕，可能是弹幕没有抓取成功
求更新弹幕功能！！！能导出XML或者ASS格式的就好了

**Comment by WhiteMinds** [comment]
4.x 支持导出成 srt
