### ISSUE TITLE
目前唯一一款能自动后台录直播的软件了

### ISSUE THREAD

**Issue by StarryDreamm** [WhiteMinds/LiveAutoRecord#49]
求作者大大能把Code打包一下发到release嘛，还有就是现在弹幕录制捕获不了了

**Comment by WhiteMinds** [comment]
> 求作者大大能把Code打包一下发到release嘛，还有就是现在弹幕录制捕获不了了

为啥要把 code 打包到 release，repo 里的有啥问题吗？
我最近三个月可能抽空更新（但不完全保证）。

**Comment by StarryDreamm** [comment]
因为release里面最新的是2019版本的，但是Code里面好像已经更新了，我也是小白不会用只能期待一下打包好的exe文件啦
