### ISSUE TITLE
录制不完整

### ISSUE THREAD

**Issue by chillia319** [WhiteMinds/LiveAutoRecord#50]
作者大大你好，我现在使用软件发现它录制视频不完整，可以正常开始录制但不会自动停止（一直停留在正在检查只能手动停止），并且只有几秒钟长度的视频，可以麻烦作者大大帮我看看是什么地方的问题吗？谢谢

**Comment by popularhoney** [comment]
作者 我也有此问题！

**Comment by WhiteMinds** [comment]
这可能是 3.0 版本时提出的问题，这个就先关掉吧，在 #120 中跟踪。
