### ISSUE TITLE
大佬，Windows系统怎么使用呢

### ISSUE THREAD

**Issue by StarryDreamm** [WhiteMinds/LiveAutoRecord#56]
win10环境需要将代码打包成exe可执行文件使用吗

**Comment by WhiteMinds** [comment]
正常编译就行，在 win 系统上编译就是 exe

**Comment by WhiteMinds** [comment]
编译流程
```
yarn
cd packages/shared && yarn build
cd packages/manager && yarn build
cd packages/electron && yarn app:build
```

**Comment by StarryDreamm** [comment]
如果没有typescript和Vue基础的话 应该怎么办才能打包呢0.0

**Comment by WhiteMinds** [comment]
那你等我发一版吧，我用 workflow 发版，目前的版本应该基本可用了，不过 b 站的弹幕支持上现在有点问题：https://github.com/ddiu8081/blive-message-listener/issues/14

**Comment by StarryDreamm** [comment]
感谢感谢大佬

**Comment by WhiteMinds** [comment]
发版了，https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.0.0

**Comment by StarryDreamm** [comment]
谢谢~
