### ISSUE TITLE
4.0.1版本无法保存设置和添加的直播间频道

### ISSUE THREAD

**Issue by mh2060** [WhiteMinds/LiveAutoRecord#58]
试了下最新上传的4.0.1版本，添加的直播间频道（用4.0.1添加的）在退出软件后，下次打开软件添加的都没了，修改的保存路径也都恢复成了默认的，就是保存不了设置和频道。百分百复现，不知道啥情况。系统是win11

**Comment by WhiteMinds** [comment]
> 试了下最新上传的4.0.1版本，添加的直播间频道（用4.0.1添加的）在退出软件后，下次打开软件添加的都没了，修改的保存路径也都恢复成了默认的，就是保存不了设置和频道。百分百复现，不知道啥情况。系统是win11

但是用 4.0.0 就都正常？
如果是的话，那确实是比较奇怪的，因为 4.0.1 虽然改了录制任务的存储方案，但是全局设置 / 录制记录都还是老的存储方案。

可能得花些时间 debug。

**Comment by mh2060** [comment]
> > 试了下最新上传的4.0.1版本，添加的直播间频道（用4.0.1添加的）在退出软件后，下次打开软件添加的都没了，修改的保存路径也都恢复成了默认的，就是保存不了设置和频道。百分百复现，不知道啥情况。系统是win11
> 
> 但是用 4.0.0 就都正常？ 如果是的话，那确实是比较奇怪的，因为 4.0.1 虽然改了录制任务的存储方案，但是全局设置 / 录制记录都还是老的存储方案。
> 
> 我台式是 win10，没复现出，得花些时间弄个 win11 测下。

我是在百度网盘下载的，只看到4.0.1版本，所以还没用过4.0.0版本，我现在下载4.0.0测试下

**Comment by mh2060** [comment]
> > 试了下最新上传的4.0.1版本，添加的直播间频道（用4.0.1添加的）在退出软件后，下次打开软件添加的都没了，修改的保存路径也都恢复成了默认的，就是保存不了设置和频道。百分百复现，不知道啥情况。系统是win11
> 
> 但是用 4.0.0 就都正常？ 如果是的话，那确实是比较奇怪的，因为 4.0.1 虽然改了录制任务的存储方案，但是全局设置 / 录制记录都还是老的存储方案。
> 
> 我台式是 win10，没复现出，得花些时间弄个 win11 测下。

测试了4.0.0版本，添加的频道直播间不会丢失，但修改的保存路径还是会恢复成默认的。
然后用4.0.1覆盖安装，添加频道也没问题了（那应该就是没装过4.0.0，直接新装4.0.1就会出现无法保存添加）），路径问题依旧

**Comment by WhiteMinds** [comment]
> （那应该就是没装过4.0.0，直接新装4.0.1就会出现无法保存添加），路径问题依旧

有道理，我明后天修下。

**Comment by mh2060** [comment]
> 新版本修了，发布了

OK，测试了，都没问题了，能保存住了。大大辛苦了
