### ISSUE TITLE
dm有关问题

### ISSUE THREAD

**Issue by Eclipsely** [WhiteMinds/LiveAutoRecord#59]
大佬您好，请问json弹幕文件如何与mp4封装在一起？能否出一个将两者合并的功能？

**Comment by WhiteMinds** [comment]
历史页面中，有一个生成 srt 字幕的功能，可以用其他工具转成 ass 然后用 ffmpeg 去合成。
目前暂时不考虑在软件内实现这个功能，因为还有其他优先级更高些的需求。
