### ISSUE TITLE
如何将保存方式从fmp4 格式改为mp4格式？

### ISSUE THREAD

**Issue by ShushuFAN** [WhiteMinds/LiveAutoRecord#60]
示例中保存格式是MP4，但我在设置中没有找到这一选项。

LAR老用户了，今天居然看到有更新，真的非常非常感谢大神！

只是对比旧版本，功能上好像做了些删减。我发现录制的暂停键、视频检查间隔、视频存储格式、视频存储位置定位，这些好像都删减了，不知道作者是出于什么考虑，后面有没有想过加回来？

再次感谢大神！

**Comment by WhiteMinds** [comment]
> 示例中保存格式是MP4，但我在设置中没有找到这一选项。

4.1.x 中，将 ffmpeg 的参数暴露出来了，你可以在设置中改保存路径为 flv 或其他格式，然后 ffmpeg 就会自动识别到 output 的类型，或者更改 ffmpeg 的参数，比如加个 -f flv。

录制暂停，你说的是设置里的 “自动检查” 选项吗？

检查间隔之后会加回来，现在功能还没做完。

视频存储格式、视频存储位置定位目前都可以在设置中修改。
