### ISSUE TITLE
请问如果根据时长自动分段呢？

### ISSUE THREAD

**Issue by ewanbandit** [WhiteMinds/LiveAutoRecord#62]
还有一个问题是，如果录制过程中主播下播，录像会正常保存吗？感谢作者大大解答

**Comment by ewanbandit** [comment]
感谢解答，以后会加入自动分段功能吗

**Comment by WhiteMinds** [comment]
> 感谢解答，以后会加入自动分段功能吗

可能不加入，需要的话可以先使用 ffmpeg 参数来完成，可以将配置调整为如下这样：

![23DC8C2DE38AFE60BC06713F44783B7C](https://user-images.githubusercontent.com/9160743/208799258-4168529b-eb40-4e97-92d9-a22278e54e70.jpg)

这样是 10s 分段一次，注意文件名要有 `%d`。
