### ISSUE TITLE
抖音平台录制问题

### ISSUE THREAD

**Issue by FreeTymeKiyan** [WhiteMinds/LiveAutoRecord#73]
添加新录制任务的时候，输入一个抖音直播房间，软件会显示正在解析，但是解析一直无法完成，无法添加录制任务

<img width="1136" alt="Screenshot 2023-02-13 at 10 23 06 PM" src="https://user-images.githubusercontent.com/1934618/218656073-82af6aa3-5fd6-4b33-90bd-134959095a19.png">

**Comment by WhiteMinds** [comment]
是最新版吗 https://github.com/WhiteMinds/LiveAutoRecord/releases/tag/v4.3.2

**Comment by dadadeju** [comment]
我也是这样

**Comment by WhiteMinds** [comment]
> 我也是这样

看下上面的问题

**Comment by dadadeju** [comment]
> > 我也是这样
> 
> 看下我上面的问题，提 issue 的时候最好带上版本号

开发者您好，我使用的是autorecord.electron-setup-4.3.2。无法解析抖音的录制，B站可以

**Comment by FreeTymeKiyan** [comment]
是最新版4.3.2

**Comment by WhiteMinds** [comment]
最近有空更新了下，在 4.4.0 中修复了该问题，没想到过去一年了 🤣
