### ISSUE TITLE
能否加入自动分段功能

### ISSUE THREAD

**Issue by joj0star** [WhiteMinds/LiveAutoRecord#75]
希望能增加一个根据文件大小自动进行分段的功能。

**Comment by WhiteMinds** [comment]
Duplicate of #62

**Comment by WhiteMinds** [comment]
目前不能，未来也不一定支持

**Comment by joj0star** [comment]
不好意思，我又遇见问题来打扰您了。
一个是设置自动分段后，直播结束后在录制历史里不会有任何视频文件显示，这样我就没法点击获取SRT字幕文件来获得字幕，录制设置里的自动获得SRT字幕文件功能也无效。这个能不能让他自动生成一个总的SRT字幕文件或者说让他在录制历史里显示一下啊。
还有一个是软件放在那里录制几个小时后界面就会卡住，录制在进行，但是软件界面点击不了，只能点右上角的最小化和关闭窗口，我想在直播结束前手动点击一下获取SRT字幕也就办不到了。

**Comment by WhiteMinds** [comment]
> 一个是设置自动分段后，直播结束后在录制历史里不会有任何视频文件显示，这样我就没法点击获取SRT字幕文件来获得字幕，录制设置里的自动获得SRT字幕文件功能也无效。这个能不能让他自动生成一个总的SRT字幕文件或者说让他在录制历史里显示一下啊。

这个不打算适配，要适配的话就直接自己做分段了，主要还是没时间。

> 还有一个是软件放在那里录制几个小时后界面就会卡住，录制在进行，但是软件界面点击不了，只能点右上角的最小化和关闭窗口，我想在直播结束前手动点击一下获取SRT字幕也就办不到了。

这个 bug 我是想修的，但是复现太耗时了，而且我这里不稳定复现，白屏之后也没有错误日志，无从下手。
目前只能在白屏后先关闭窗口，再从托盘菜单里开个新窗口出来。

**Comment by joj0star** [comment]
好的，SRT文件我可以在直播停止前把它点出来。
卡住这个我还是不动它了，能录制就行，感觉关闭窗口的话，文件会损坏。
我主要用来传B站，设置的1小时自动分段录制MP4格式。最近发现手动终止录制或者网络波动等原因导致的意外分段传B站会显示转码失败。

**Comment by WhiteMinds** [comment]
> 卡住这个我还是不动它了，能录制就行，感觉关闭窗口的话，文件会损坏。

窗口是纯 UI 层，不涉及到录制逻辑的部分，所以关闭没有影响。

> 我主要用来传B站，设置的1小时自动分段录制MP4格式。最近发现手动终止录制或者网络波动等原因导致的意外分段传B站会显示转码失败。

这个原因不太确定，你可以试试把损坏的文件用 ffmpeg 或者其他软件先处理下试试。
