### ISSUE TITLE
FFMPEG可以实现视频长度切割功能吗？ 

### ISSUE THREAD

**Issue by StarryDreamm** [WhiteMinds/LiveAutoRecord#76]
查询了一下FFMPEG中的各类参数，在后续加上-t 3600 （单位是s？还是ms？），就能实现每个视频的长度都是1个小时了嘛

**Comment by joj0star** [comment]
这个按时长分段问题我也问过，作者大大在issues #62 有过回答。

**Comment by WhiteMinds** [comment]
> 好的，谢谢你~ 那请问1小时的话 是将下面的代码添加到FFMPEG的参数中就可以了吗？ -ss 0 -f segment -segment_time 01:00:00

还需要调整命名规则，参考 #62
