### ISSUE TITLE
尝试添加FFMPEG添加时长分段参数后发现bug

### ISSUE THREAD

**Issue by StarryDreamm** [WhiteMinds/LiveAutoRecord#77]
### 录制时FFMPEG的全部参数：
`FFMPEG 录制参数
-user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36 -i https://stream-jilin-ctt-111-26-38-136.edgesrv.com:443/live/5551871rfpAxePMa_1024p.flv?wsAuth=fecf2674f93518442c4e281cef986467&token=web-h5-0-5551871-6b46f0ba50145cd09fcbb5bed2e7b120186fa3c4400ae2e5&logo=0&expire=0&did=b5337f089d7644bb82113f8d8cd7744f&pt=2&st=0&vhost=play4&origin=tct&mix=0&isp=scdncttjiljl&pushdouyu=1 -y -ss 0 -f segment -segment_time 00:15:00 -c copy -movflags frag_keyframe -min_frag_duration 60000000 D:\_video\斗鱼\Minana呀\2023-03-25_21-32-25%d.flv`
### 路径：
D:\_video\{platform}\{owner}\{year}-{month}-{date}_{hour}-{min}-{sec}%d.mp4
### FFMPEG参数：
-ss 0 -f segment -segment_time 00:15:00 -c copy -movflags frag_keyframe -min_frag_duration 60000000

视频可正常生成，但无法播放(播放器potplayer，win10自带播放器，其余播放器均尝试过，在格式工厂无法转码)，将路径末尾的视频格式改成flv却可以正常生成播放；将FFMPEG参数改回默认，格式为mp4 可以正常录制，视频无法播放。

由于卸载重装多遍也无法解决，想问问这是个bug还是个人其他原因造成的？ 烦请分析一下

**Comment by WhiteMinds** [comment]
有试过用软件自带的播放器吗？

**Comment by StarryDreamm** [comment]
> 有试过用软件自带的播放器吗？

试过，黑屏，显示播放错误

**Comment by WhiteMinds** [comment]
那挺奇怪的，默认参数我在 win10 上试过应该是能正常播放的，是不是参数没有完全调回默认状态？

**Comment by StarryDreamm** [comment]
> 那挺奇怪的，默认参数我在 win10 上试过应该是能正常播放的，是不是参数没有完全调回默认状态？

调不回默认参数了，，没有备份之前的参数。。。

**Comment by WhiteMinds** [comment]
默认参数可以看这里
https://github.com/WhiteMinds/LiveAutoRecord/blob/master/packages/manager/src/manager.ts#L230 
https://github.com/WhiteMinds/LiveAutoRecord/blob/master/packages/manager/src/manager.ts#L235

**Comment by WhiteMinds** [comment]
> 格式为mp4 可以正常录制，视频无法播放。

这是因为 mp4 播放所需要的信息是在录制完成后才写入的，终止录制后应该就能播放了。

**Comment by StarryDreamm** [comment]
> > 格式为mp4 可以正常录制，视频无法播放。
> 
> 这是因为 mp4 播放所需要的信息是在录制完成后才写入的，终止录制后应该就能播放了。 这也是软件默认用 fmp4 的原因，fmp4 可以边录边播。

刚刚又试了几下，
默认参数下录制，在任务管理器上看到FFMPEG有下载但是**没有**磁盘写入，内存缓慢增加1MB/s，测试30秒最终的mp4文件只有36字节，无法播放；
默认参数上修改为flv格式，任务管理器上看到FFMPEG有下载但是有磁盘写入，内存无增加，可正常播放。

那应该是fmp4/mp4的问题嘛？ 不过问题不大 用flv就好了

**Comment by WhiteMinds** [comment]
> 默认参数下录制，在任务管理器上看到FFMPEG有下载但是没有磁盘写入，内存缓慢增加1MB/s，测试30秒最终的mp4文件只有36字节，无法播放；

默认参数给的是 1 分钟一个片段，所以 1 分钟后才会有写入，具体原因可以看 https://github.com/WhiteMinds/LiveAutoRecord/blob/master/packages/manager/src/manager.ts#L242

**Comment by StarryDreamm** [comment]
> > 默认参数下录制，在任务管理器上看到FFMPEG有下载但是没有磁盘写入，内存缓慢增加1MB/s，测试30秒最终的mp4文件只有36字节，无法播放；
> 
> 默认参数给的是 1 分钟一个片段，所以 1 分钟后才会有写入，具体原因可以看 https://github.com/WhiteMinds/LiveAutoRecord/blob/master/packages/manager/src/manager.ts#L242

0.0懂了 谢谢大佬
