### ISSUE TITLE
页面不响应

### ISSUE THREAD

**Issue by CHDKBL** [WhiteMinds/LiveAutoRecord#84]
你好，我开着软件录制时，时间久了页面会点击不了任何按钮，只能关闭后重新在右下角的小标内打开才能点击，请问是bug吗。

**Comment by WhiteMinds** [comment]
是的，老 bug 了，但是找不到稳定复现的方法，所以暂时修不了

**Comment by WhiteMinds** [comment]
在 https://github.com/WhiteMinds/LiveAutoRecord/commit/493e29385e40820d6601ece30b3a6b1a3b38dc1d 中修复

**Comment by WhiteMinds** [comment]
对于此 issue 的修复现在包含到了 4.3.4 版本中 https://github.com/WhiteMinds/LiveAutoRecord/releases
