### ISSUE TITLE
长时间挂在后台CPU占用异常

### ISSUE THREAD

**Issue by esclm** [WhiteMinds/LiveAutoRecord#92]
长时间挂在后台，无论是否有录制，CPU会有一个核心被几乎占满

**Comment by WhiteMinds** [comment]
我没观测到过这个情况，是 win10 + LARv4.3.2 吗？
如果确实会出现这种情况，感觉说不定就是之前一直没定位到的白屏 bug 的原因 (#84 ）

**Comment by WhiteMinds** [comment]
版本号以后应该会加一个。
日志其实有一些，参考这里 https://github.com/WhiteMinds/LiveAutoRecord/issues/68#issuecomment-1383315031

但是这个问题不知道日志能不能记录到，因为关了自动检查之后，理论上一直在运行的只有 8085 端口的后端服务了 https://github.com/WhiteMinds/LiveAutoRecord/blob/a57b176d4adf2a6c2c5d8734994187d5f0d1ef51/packages/http-server/src/index.ts#L51-L52
如果你计算机上没有什么程序一直在访问 8085 端口的话，就不太确定是哪里有 bug 了。

我最近应该没时间远程调试，如果你确实比较需要解决这个问题的话，可以试试用 https://github.com/pd4d10/debugtron 和 https://stackoverflow.com/questions/54835751/opening-chromium-devtools-in-production-builds-of-electron-apps-without-source-c 调试下（或者直接按照本仓库的流程在本地编译一个调试版本），就是到性能面板录制下是哪些东西占了性能。

<img width="746" alt="image" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/3f9ea34a-f165-48c8-be58-b25dcf4ef96e">

**Comment by esclm** [comment]
好棒的调试方法 ~~孤陋寡闻 有时间得去学着调试~~

哈哈其实cpu的占用不会很有影响，就算有影响重启一下就能解决

没有很大的解决这个问题的需求 只是在软件层面看这么高的性能浪费值得提一个issue打扰一下作者

***
## 等重现和记录

等了几天才重现问题

和界面应该确实没有关系，界面的记录很正常

然后下面是electron/js2c/browser_in的Inpect截图（一个开启自动检测 一个没有）

<img src="https://github.com/WhiteMinds/LiveAutoRecord/assets/71742130/cde39fb8-4e3a-44db-a41f-13990175a6fd" height="100">

<img src="https://github.com/WhiteMinds/LiveAutoRecord/assets/71742130/38b714c1-8a10-4373-b9cf-f2446e9c30ac" height="200">

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/71742130/c7aec6f7-134a-40dd-a890-782e2c527006)

感觉异步函数节流函数导致没停

看到这我就看了眼磁盘写入一直在跳变，然后就发现最新一次录制的json记录在以很快的速度被反复写入

~~怪不得等了这么久才重现问题 之前把自动录制关了~~

## 复现

测过几次后发现录制自动结束和手动结束ffmpeg进程（这俩好像在ffmpeg输出上没啥区别吧）都会造成反复写入json数据

一个任务计划定期重启解决，不过如果作者有精力想修一下就更好了

~~可惜我没有能力看懂ts~~

**Comment by WhiteMinds** [comment]
喔，描述的很清晰，专业 🤣

我等最近有空的时候尝试复现看看。

**Comment by WhiteMinds** [comment]
看起来是一个小问题，我做了个简单的修复，你可以在这里看到改动以及测试版本的下载（Action 的 Artifacts 里）：
https://github.com/WhiteMinds/LiveAutoRecord/commit/031f69cf426ed19182da666a7cfec47a3cb86d61#commitcomment-115771540

你下载试试看还会不会出现这个问题。

**Comment by deeprism** [comment]
当我录制抖音时，CPU 使用率和写入数据磁盘的次数都异常高。
这个频道也是如此，而且是在直播结束后发生的。
我正在使用最新的测试版

**Comment by WhiteMinds** [comment]
> 看起来是一个小问题，我做了个简单的修复，你可以在这里看到改动以及测试版本的下载（Action 的 Artifacts 里）： [031f69c#commitcomment-115771540](https://github.com/WhiteMinds/LiveAutoRecord/commit/031f69cf426ed19182da666a7cfec47a3cb86d61#commitcomment-115771540)
> 
> 你下载试试看还会不会出现这个问题。

该修复现在包含到了 4.3.4 版本中 https://github.com/WhiteMinds/LiveAutoRecord/releases

**Comment by WhiteMinds** [comment]
> 当我录制抖音时，CPU 使用率和写入数据磁盘的次数都异常高。 这个频道也是如此，而且是在直播结束后发生的。 我正在使用最新的测试版

听起来可能不是一个问题，录制结束后 ffmpeg 可能会继续占用几分钟 CPU 和 IO 读写，因为它在写入 metadata、keyframes 等。
如果不是 ffmpeg 进程在占用，那你可以试下最新版 4.3.4，如果问题仍然存在，可以新开个 issue 处理。
