### ISSUE TITLE
某些用户名出现的错误

### ISSUE THREAD

**Issue by deeprism** [WhiteMinds/LiveAutoRecord#93]
如果用户名后面有一个"."，则不记录，并且会创建一个无法删除的文件夹
我通过在默认保存路径{platform}\{owner}\{year}owner}之后添加适当的词来解决这个错误
例如 {platform}\{owner}video\{year}

**Comment by WhiteMinds** [comment]
是 owner 会出现 `.` 吗，有没有具体的直播间例子

**Comment by deeprism** [comment]
https://live.douyin.com/937431186447

在这里发生的

**Comment by jm3720343** [comment]
我也是，但我是在目录再创建没有“.”的文件夹，就能点进去了。
