### ISSUE TITLE
在服务端部署后，访问服务端、前端端口均显示 Cannot GET

### ISSUE THREAD

**Issue by dzwzqlx** [WhiteMinds/LiveAutoRecord#97]
如图，防火墙端口已打开，客户端已加 --host，访问服务端端口 8085 和前端端口 4173 均显示 Cannot GET，
其中访问服务端端口后，服务端命令行会输出404信息；
访问客户端端口后没有反应

![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/87611314/d8765fbb-ffb2-4b3c-9c8f-599d8416178c)

尝试了几个地址都不行
![image](https://github.com/WhiteMinds/LiveAutoRecord/assets/87611314/948d8a58-6125-42c5-baea-905f388a646a)

**Comment by WhiteMinds** [comment]
`Cannot GET /` 这种信息一般是 nodejs 给的，也就是说这个端口应该确实可以访问并且有 node 程序监听到了。
但是以防万一，你可以先按照这里说的，为前端的命令加上 --host 来暴露给所有网卡。

<img width="231" alt="image" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/cf64f19e-30e2-4207-9cf3-6a701c9470dc">

后端的确实没有首页所以返回 404 是合理的，测试的话可以试试访问 http://backend-ip:8085/api/settings
