### ISSUE TITLE
无法解析抖音直播间

### ISSUE THREAD

**Issue by ilikeulinux** [WhiteMinds/LiveAutoRecord#98]
![QQ截图20230806160914](https://github.com/WhiteMinds/LiveAutoRecord/assets/41497656/959a7dd1-a7bf-4884-9d33-ec990a2e9595)
软件版本：4.3.4
我是今天早上开始使用这款软件的。
添加了3个主播后，无法再继续添加了，一直处于解析状态。
换了十几个主播的直播间链接都是相同的问题。
重新运行软件、重启电脑、重新拨号上网，都无法解决。

**Comment by wxz6079** [comment]
你要不试试只填链接里的那个数字？

**Comment by WhiteMinds** [comment]
<img width="787" alt="image" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/795333a9-0406-47f9-923f-bda3d11bf9bd">

我这里无法复现，有没有可能是你使用了什么代理通道出问题了？

除了关闭代理外，还可以试试直接访问这个直播间，看看是否能在网页上正常播放。

如果一切正常，可以看看日志里的报错信息是什么，win 系统中的日志文件夹在 `%LOCALAPPDATA%\live-auto-record\Log`

**Comment by ilikeulinux** [comment]
> 你要不试试只填链接里的那个数字？

我试过的，一样的问题。

**Comment by OriX0** [comment]
我大概知道原因，

> > 你要不试试只填链接里的那个数字？
> 
> 我试过的，一样的问题。

我大概知道原因，因为软件默认是1s检测间隔 这个实际上太快了  会被平台临时屏蔽 然后返回的data=''  设置间隔15+即可

**Comment by WhiteMinds** [comment]
该问题后续应该通过这个 #102 解决
