### ISSUE TITLE
无法检测抖音直播开播

### ISSUE THREAD

**Issue by ilikeulinux** [WhiteMinds/LiveAutoRecord#99]
![QQ截图20230807092115](https://github.com/WhiteMinds/LiveAutoRecord/assets/41497656/8a839ea9-9cd8-4b23-9c03-327b1ca5634a)
如上图所示，播主已经开播很久了，但软件不能检测到开播了，所以一直没有进行录像。

软件版本：4.3.4
重新运行软件、重启电脑、重新拨号上网，均无法解决上述问题。

**Comment by WhiteMinds** [comment]
<img width="394" alt="image" src="https://github.com/WhiteMinds/LiveAutoRecord/assets/9160743/b9deb2a4-5c70-405a-997e-848d8f77370d">

无法复现，参考这里处理 https://github.com/WhiteMinds/LiveAutoRecord/issues/98#issuecomment-1667896666

**Comment by OriX0** [comment]
> ![QQ截图20230807092115](https://user-images.githubusercontent.com/41497656/258679916-8a839ea9-9cd8-4b23-9c03-327b1ca5634a.jpg) 如上图所示，播主已经开播很久了，但软件不能检测到开播了，所以一直没有进行录像。
> 
> 软件版本：4.3.4 重新运行软件、重启电脑、重新拨号上网，均无法解决上述问题。

其实就是检测间隔太低了 然后你请求多了 抖音返回的data等于空 无法及时更新  建议全局设置 15s以上的检测间隔

**Comment by WhiteMinds** [comment]
#102
